---
name: Add/Update Movie Theme Song
description: Submit a new Movie theme song, or update an existing one.
labels:
  - request-movie
title: '[MOVIE]: '
body:
  - type: input
    id: themoviedb_url
    attributes:
      label: TheMovieDB URL
      description: The URL to the movie on TheMovieDB (e.g. https://www.themoviedb.org/movie/10378-big-buck-bunny).
    validations:
      required: true
  - type: input
    id: youtube_theme_url
    attributes:
      label: YouTube Theme Song Video URL
      description: The URL to the theme song YouTube video (e.g. https://www.youtube.com/watch?v=I4SREhn7yJY).
    validations:
      required: true
