---
name: Add/Update Game Theme Song
description: Submit a new Game theme song, or update an existing one.
labels:
  - request-game
body:
  - type: input
    id: igdb_url
    attributes:
      label: IGDB URL
      description: The URL to the movie on IGDB (e.g. https://www.igdb.com/games/goldeneye-007).
    validations:
      required: true
  - type: input
    id: youtube_theme_url
    attributes:
      label: YouTube Theme Song Video URL
      description: The URL to the theme song YouTube video (e.g. https://www.youtube.com/watch?v=FV7GI2LxWRw).
    validations:
      required: true
