---
name: CI Tests
permissions: {}

env:
  NODE_VERSION: '24'
  PYTHON_VERSION: '3.14'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38  # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --locked --extra dev --python "${PYTHON_VERSION}" --no-python-downloads

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Test with pytest
        id: pytest
        shell: bash
        run: uv run --no-sync python -m pytest tests

      - name: Test with Jest
        id: jest
        if: always()
        env:
          FORCE_COLOR: true
        shell: bash
        run: npm test

      - name: Upload test coverage
        # any except cancelled or skipped
        if:
          always() &&
          (
            steps.pytest.outcome == 'success' ||
            steps.pytest.outcome == 'failure' ||
            steps.jest.outcome == 'success' ||
            steps.jest.outcome == 'failure'
          ) &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          fail_ci_if_error: true
          files: ./coverage/python-coverage.xml,./coverage/coverage-final.json
          report_type: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results
        # any except cancelled or skipped
        if:
          always() &&
          (
            steps.pytest.outcome == 'success' ||
            steps.pytest.outcome == 'failure' ||
            steps.jest.outcome == 'success' ||
            steps.jest.outcome == 'failure'
          ) &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          fail_ci_if_error: true
          files: ./junit-python.xml,./junit.xml
          report_type: test_results
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
