---
name: Comment command
permissions: {}

on:
  issue_comment:
    types:
      - created

jobs:
  github-env:
    name: GitHub Env Debug
    permissions:
      contents: read
    uses: LizardByte/.github/.github/workflows/__call-github-env.yml@master

  comment_command:
    name: Comment command ${{ github.event.issue.number }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if:
          github.actor != 'LizardByte-bot' &&
          (
            startsWith(github.event.comment.body, '@LizardByte-bot') ||
            startsWith(github.event.comment.body, '/question')
          )
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Comment command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_AUTHOR_ID: ${{ github.event.comment.user.id }}
          COMMENT_ID: ${{ github.event.comment.id }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_AUTHOR_ID: ${{ github.event.issue.user.id }}
          # https://regex101.com/r/vHEc61/1
          YT_REGEX: '^((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube(-nocookie)?\.com|youtu.be))(\/(?:[\w\-]+\?v=|embed\/|v\/)?)([\w\-]+)(\S+)?$'  # yamllint disable-line rule:line-length
        if:
          github.actor != 'LizardByte-bot' &&
          (
            startsWith(github.event.comment.body, '@LizardByte-bot') ||
            startsWith(github.event.comment.body, '/question')
          )
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          script: |
            const {run} = require('./src/github-scripts/comment-command.js')
            await run({github, context})
