---
name: Comment command
permissions: {}

on:
  issue_comment:
    types:
      - created

jobs:
  github-env:
    name: GitHub Env Debug
    permissions:
      contents: read
    uses: LizardByte/.github/.github/workflows/__call-github-env.yml@master

  comment_command:
    name: Comment command ${{ github.event.issue.number }}
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check if member
        id: member
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            "/orgs/${GITHUB_REPOSITORY_OWNER}/members/${GITHUB_ACTOR}" || echo "member=false" >> "${GITHUB_OUTPUT}"

      - name: Checkout
        if:
          steps.member.outputs.member != 'false' &&
          github.actor != 'LizardByte-bot'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Comment command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_ID: ${{ github.event.comment.id }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          # https://regex101.com/r/vHEc61/1
          YT_REGEX: '^((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube(-nocookie)?\.com|youtu.be))(\/(?:[\w\-]+\?v=|embed\/|v\/)?)([\w\-]+)(\S+)?$'  # yamllint disable-line rule:line-length
        if:
          steps.member.outputs.member != 'false' &&
          github.actor != 'LizardByte-bot'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          script: |
            const {run} = require('./src/github-scripts/comment-command.js')
            await run({github, context})
