---
name: Python Tests
permissions: {}

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pytest:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.14'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[dev]"

      - name: Install npm dependencies
        run: npm install --ignore-scripts

      - name: Test with pytest
        id: test
        shell: bash
        run: python -m pytest tests

      - name: Upload test coverage
        # any except cancelled or skipped
        if:
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354  # v6.0.1
        with:
          fail_ci_if_error: true
          files: ./coverage/python-coverage.xml
          flags: ${{ runner.os }}
          report_type: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results
        # any except cancelled or skipped
        if:
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354  # v6.0.1
        with:
          fail_ci_if_error: true
          files: ./junit-python.xml
          flags: ${{ runner.os }}
          report_type: test_results
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
