---
name: Relabel Issue
permissions: {}

on:
  issues:
    types:
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}

jobs:
  relabel_issue:
    name: Relabel issue ${{ github.event.issue.number }}
    # we want to skip edits made by bots (especially title edits)
    if: github.actor != 'LizardByte-bot' && github.actor != 'renovate[bot]'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Relabel issue ${{ github.event.issue.number }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          script: |
            const {run} = require('./src/github-scripts/relabel-issue.js')
            await run({github, context})
